version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
    - ./frontend/app:/usr/share/nginx/html
    stdin_open: true
    tty: true
    restart: unless-stopped
