FROM python:3.9-slim

WORKDIR /app

# Python bağımlılıkları
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# React uygulamasını kopyala ve bağımlılıkları yükle
COPY GameLibrary/package.json GameLibrary/package-lock.json ./GameLibrary/
RUN cd GameLibrary && npm install

# Tüm uygulamayı kopyala
COPY . .

# Uygulamaları çalıştırmak için startup script
COPY startup.sh .
RUN chmod +x startup.sh

EXPOSE 3000 5000

CMD ["./startup.sh"]

# ---------------

# FROM python:3.9-slim

# WORKDIR /app

# COPY . /app

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "app.py"]

