groups:
- name: system-alerts
  rules:
  - alert: HighCPUUsage
    expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m]))) * 100) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU Usage ({{ $value }}%)"
      description: "CPU usage is above 80% on {{ $labels.instance }}"
