- name: VM'e Docker kurulumu yap
  hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Gerekli paketleri kur
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Docker GPG anahtarını indir
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker-gpg-key
        mode: '0644'

    - name: GPG anahtarını doğru formatta ekle
      shell: |
        cat /tmp/docker-gpg-key | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg
        chmod 644 /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        executable: /bin/bash

    - name: Docker repo ekle
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes

    - name: Docker paketlerini kur
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Docker servisini başlat
      service:
        name: docker
        state: started
        enabled: true

    - name: Geçici dosyayı temizle
      file:
        path: /tmp/docker-gpg-key
        state: absent